# -*- coding: utf-8 -*-
"""KNN3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14h5Gyosigw8YY9Ds-rKm6RcasUOvisZ_
"""

import numpy as np
import pandas as pd
df=pd.read_csv("/content/heart.csv")
df

print(df.columns)

df.head()

df.tail()

df.shape

x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
x
y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)
y_test

from sklearn.preprocessing import StandardScaler 
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_test

from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
print(y_pred)

from sklearn.metrics._plot.confusion_matrix import confusion_matrix 
from sklearn.metrics import classification_report,accuracy_score,ConfusionMatrixDisplay
labels=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']
result=confusion_matrix(y_test,y_pred)
cm=ConfusionMatrixDisplay(result,display_labels=labels)
cm.plot()
score=accuracy_score(y_test,y_pred)
print(result)
score=accuracy_score(y_test,y_pred)
print(score)